---
title: "Midterm"
author: "Sylvia Baeyens"
date: "due 10/22/2021"
output:
  github_document:
    html_preview: false
  html_document: default
  word_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```


```{r packages, echo= FALSE, include= FALSE}
#including necessary libraries
library(tidyverse)
library(tidytext)
library(dplyr)
library(ggplot2)
library(R.utils)
library(data.table)
```

## Introduction


## Methods

```{r meat data cleanup, echo= FALSE, include= FALSE}
#reading in meat dataset
# meatData= data.table::fread("MeatConsumption.csv") 
# meatData = meatData %>%
#   rename(consumption = "Value", year="TIME")

meatData= data.table::fread("meat-supply-per-person.csv") 
colnames(meatData) = c("COUNTRY", "code", "year", "consumption")


#check for missing data
meatData[,table(is.na(consumption))]
# no missing data
```

```{r anemia data cleanup, echo= FALSE, include= FALSE}
#reading in all 3 anemia data sets: mild, moderate & severe
#changing mean variable to be representative of the type of anemia
mildAnemia= data.table::fread("MildAnemia.CSV") 
mildAnemia = mildAnemia %>%
  rename(COUNTRY = "ADM0_NAME", mildPct = "mean")

modAnemia= data.table::fread("ModerateAnemia.CSV") 
modAnemia = modAnemia %>%
  rename(COUNTRY = "ADM0_NAME", modPct = "mean")

sevAnemia= data.table::fread("SevereAnemia.CSV") 
sevAnemia = sevAnemia %>%
  rename(COUNTRY = "ADM0_NAME", sevPct = "mean")

# finding mean Anemia pct by country & year
mildAvg = mildAnemia[,.(
  mildPct = mean(mildPct,na.rm = TRUE)
  ), by = c("COUNTRY", "year")]
modAvg = modAnemia[,.(
  modPct = mean(modPct,na.rm = TRUE)
  ), by = c("COUNTRY", "year")]
sevAvg = sevAnemia[,.(
  sevPct = mean(sevPct,na.rm = TRUE)
  ), by = c("COUNTRY", "year")]

# merging all 3 anemia data frames
TotalAnemia = merge(
  x = mildAvg,
  y = modAvg,
  all.x = TRUE, all.y = FALSE
)

TotalAnemia = merge(
  x = TotalAnemia,
  y = sevAvg,
  all.x = TRUE, all.y = FALSE
)

#check for any missing data
TotalAnemia[,table(is.na(mildPct))]
TotalAnemia[,table(is.na(modPct))]
TotalAnemia[,table(is.na(sevPct))]
#no missing data
```

```{r merging all data, echo= FALSE, include= FALSE}
#selecting necessary info from meat data & only considering beef

#merging meat & anemia data
TotalData = merge(
  x = TotalAnemia,
  y = meatData,
  all.x = TRUE, all.y = FALSE
)

#download country code csv
countryCodes= "countryCodes.csv"
if(!file.exists(countryCodes)){
   download.file("https://pkgstore.datahub.io/JohnSnowLabs/country-and-continent-codes-list/country-and-continent-codes-list-csv_csv/data/b7876b7f496677669644f3d1069d3121/country-and-continent-codes-list-csv_csv.csv", destfile = countryCodes)}

countryCodes= data.table::fread(countryCodes)
countryCodes = countryCodes %>%
  rename(CONTINENT = "Continent_Name", code= "Three_Letter_Country_Code") %>%
  select(code, CONTINENT)

#merging country code data frame & Total Data data frame so that the meat data frame includes continent name
TotalData = merge(
  x = TotalData,
  y = countryCodes,
  all.x = TRUE, all.y = FALSE,
  by = "code"
)


TotalData[,table(is.na(consumption))]
#missing 392/1640 -> some whole countries are missing, some years for specific countries missing

TotalData = na.omit(TotalData)
#removed all rows with NAs -> 1258 obs 

summary(TotalData)
#no data looks out of the ordinary

hist(TotalData$consumption)
hist(TotalData$mildPct)
hist(TotalData$modPct)
hist(TotalData$sevPct)

```


## Preliminary Results

```{r}

ggplot(TotalData,aes(x=consumption, y=(mildPct+modPct+sevPct)*100)) +
  geom_point() +
  geom_smooth(method= "lm") +
  ggtitle("Visualizing the Relationship between Anemia & Meat Consumption in Underdeveloped Countries")+
  ylab('Total Percentage of Women 15-49 with Anemia of any Severity')+
  xlab('Meat Consumption (kg/capital/year')

TotalData %>%
  filter("Asia"== CONTINENT) %>%
  ggplot(aes(x=year, y=(mildPct+modPct+sevPct)*100)) +
    facet_wrap(~COUNTRY, nrow= 8) +
    geom_point() +
    geom_smooth(method= "lm")+
    ggtitle("Anemia in Young Women in underdeveloped Asian Countries")+
    theme(axis.text.x = element_text(angle = 45))+
    ylab('Total Percentage of Women 15-49 with Anemia of any Severity')

TotalData %>%
  filter("Africa"== CONTINENT) %>%
  ggplot(aes(x=year, y=(mildPct+modPct+sevPct)*100)) +
    facet_wrap(~COUNTRY, nrow= 8) +
    geom_point() +
    geom_smooth(method= "lm")+
    ggtitle("Anemia in Young Women in underdeveloped African Countries")+
    theme(axis.text.x = element_text(angle = 45))+
    ylab('Total Percentage of Women 15-49 with Anemia of any Severity')

TotalData %>%
  filter("South America"== CONTINENT) %>%
  ggplot(aes(x=year, y=(mildPct+modPct+sevPct)*100)) +
    facet_wrap(~COUNTRY, nrow= 3) +
    geom_point() +
    geom_smooth(method= "lm")+
    ggtitle("Anemia in Young Women in underdeveloped South American Countries")+
    theme(axis.text.x = element_text(angle = 45))+
    ylab('Total Percentage of Women 15-49 with Anemia of any Severity')

TotalData %>%
  filter("North America"== CONTINENT) %>%
  ggplot(aes(x=year, y=(mildPct+modPct+sevPct)*100)) +
    facet_wrap(~COUNTRY, nrow= 3) +
    geom_point() +
    geom_smooth(method= "lm")+
    ggtitle("Anemia in Young Women in underdeveloped North American Countries")+
    theme(axis.text.x = element_text(angle = 45))+
    ylab('Total Percentage of Women 15-49 with Anemia of any Severity')
```

```{r}

#looking at averages for each country

TotalDataAvg = TotalData[,.(
  consumption = mean(consumption,na.rm = TRUE),
  mildPct = mean(mildPct,na.rm = TRUE),
  modPct = mean(modPct,na.rm = TRUE),
  sevPct = mean(sevPct,na.rm = TRUE)
),by = "COUNTRY"]

TotalDataAvg %>%
  arrange(consumption) %>%
  ggplot(aes(x=consumption, y=COUNTRY))+
  geom_bar(stat= "identity") 
```

## Conclusion
